#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    arm_pot_left,   sensorPotentiometer)
#pragma config(Sensor, in2,    arm_pot_right,  sensorPotentiometer)
#pragma config(Sensor, in3,    hand_pot,       sensorPotentiometer)
#pragma config(Sensor, in4,    power_expander, sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           shooter_top,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           base_left1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           base_right1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           base_left2,    tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port5,           base_right2,   tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           arm_left,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           arm_right,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           hand,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          shooter_bottom, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "types.c"
#include "constants.c"
#include "autoconfig.c"
#include "motors.c"
#include "sensors.c"
#include "pidcontrol.c"
#include "base.c"
#include "arm.c"
#include "hand.c"
#include "shooter.c"
#include "intake.c"
#include "lcd.c"
#include "dunk.c"
#include "tasks.c"
#include "setup.c"
#include "auto.c"
#include "driver.c"
